services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "BDDEFESACIVIL"
    ports:
      - "3307:3307"
    volumes:
      - /backend/mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
networks:
  db:
    driver: bridge