import * as yup from 'yup';

export const schemaRelatorio = yup.object({
	memorando: yup.string().required('Informe o memorando.'),
	enfermos: yup.number().required(),
	relatorio: yup.string().required(),
	processo: yup.string().required(),
	assunto: yup.string().required(),
	interdicao: yup.number().required(),
	areaAfetada: yup.number().required(),
	tipoConstrucao: yup.number().required(),
	tipoTalude: yup.number().required(),
	situacao: yup.number().required(),
	vegetacao: yup.number().required(),
	oficio: yup.string().required(),
	encaminhamento: yup.string().required(),
	observacoes: yup.string().required(),
	danosMateriais: yup.bool().required(),
	dataGeracao: yup.date().required(),
	dataAtendimento: yup.date().required(),
	dadosVistoria: yup.object({
		desmoronamento: yup.bool().required(),
		deslizamento: yup.bool().required(),
		esgoto_escoamento: yup.bool().required(),
		erosao: yup.bool().required(),
		inundacao: yup.bool().required(),
		incendio: yup.bool().required(),
		arvores: yup.bool().required(),
		infiltracao_trinca: yup.bool().required(),
		judicial: yup.bool().required(),
		monitoramento: yup.bool().required(),
		transito: yup.bool().required(),
	}),
	afetados: yup.object({
		adultos: yup.number().required(),
		criancas: yup.number().required(),
		idosos: yup.number().required(),
		especiais: yup.number().required(),
		mortos: yup.number().required(),
		feridos: yup.number().required(),
		enfermos: yup.number().required(),
	}),
	animais: yup.object({
		caes: yup.number().required(),
		gatos: yup.number().required(),
		aves: yup.number().required(),
		equinos: yup.number().required(),
	}),
	fotos: yup.object({
		url: yup.string().required(),
	}),
});
